### ISSUE TITLE
Main route not working since release 0.2.4

### ISSUE THREAD

**Issue by benji1000** [Moxxie/MoxRouter#2]
Hello,

I've been using your router for a few months now, it works great! Problem is, when I update it to version 0.2.5, my main route is ignored, and the `notFound` route is used instead when I try to access the index page. When I revert back to version 0.2.3, the main route is not ignored.

To be clear, this is ignored in versions 0.2.4 and 0.2.5 :

```
$router->get('/', function(){});
```

And this route is loaded instead:

```
$router->notFound(function(){});
```

When I try to access https://example.com/.

Nothing else changes in my code. Tested on PHP 7.2.4 and 7.3.8.

Thank you for your help.

**Comment by Moxxie** [comment]
Hey!

Thanks for reporting that bug! I didn't realize anyone was using this :)

I've released, hopefully, a fix for this.

Please don't hesitate if you have any questions or ideas.

Best regards,
Moxxie

**Comment by benji1000** [comment]
Haha, yes, I know the feeling of developing something and feeling like no one is using it :) I love MoxRouter because it's clean and simple. It's very practical to be able to use a router and not having to deal with a whole framework. I use it for a few projects of mine, as well as for my company's blog.

Anyway, I can confirm that the issue is fixed. Thank you!
